{{- if .Values.httpReceiver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inboxbooster-mailer.http-receiver.serviceAccountName" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-receiver
  {{- if .Values.httpReceiver.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.httpReceiver.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
