# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mxserver
  labels:
    app: mxserver
spec:
  containers:
    - name: mxserver
      image: inboxbooster/mxserver
      ports:
        - containerPort: 25
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
