# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mxserver
  labels:
    app: mxserver
spec:
  containers:
    - name: mxserver
      image: inboxbooster/mxserver
      ports:
        - containerPort: 25
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command: [
              "python3", "/app/shutdown.py",
              "--global-config-file=/configs/inboxbooster-mailer-global.yaml",
              "--customer-config-file=/configs/inboxbooster-mailer-customer.yaml"
            ]
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
