apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-08T19:41:20Z"
  name: mxserver
  namespace: default
  resourceVersion: "109776480"
  uid: 2a09cc54-14e8-4e7f-9b9b-7e203a272f1f
spec:
  clusterIP: 10.3.29.28
  clusterIPs:
  - 10.3.29.28
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: my-port
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: mxserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
