apiVersion: v1
kind: Service
metadata:
  name: {{ include "inboxbooster-mailer.receiver.fullname" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: receiver
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.receiver.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.receiver.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inboxbooster-mailer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: receiver