{{- if .Values.receiver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inboxbooster-mailer.receiver.serviceAccountName" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: receiver
  {{- if .Values.receiver.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.receiver.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
