{{- if .Values.mxServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inboxbooster-mailer.mx-server.serviceAccountName" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: mx-server
  {{- if .Values.mxServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.mxServer.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
