{
 "title": "Inboxbooster-Mailer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Inboxbooster Mailer Latest Throughput (last 5min)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "# Receiver Pushed Emails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nbr_emails_enqueued_total{job=\"receiver\"}[5m]))",
     "legendFormat": "# Receiver Pushed Emails"
    }
   ]
  },
  {
   "title": "# Transformer Poll",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(transformer_polled_primary_total{job=\"transformer\"}[5m])) + sum(increase(transformer_polled_default_total{job=\"transformer\"}[5m]))",
     "legendFormat": "# Tranformer Poll"
    }
   ]
  },
  {
   "title": "# Transformer Push",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(transformer_pushed_total{job=\"transformer\"}[5m]))",
     "legendFormat": "# Transformer Push"
    }
   ]
  },
  {
   "title": "# Postfix Poll Emails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postfix_emails_polled_total{job=\"postfix\"}[5m]))",
     "legendFormat": "# Postfix Poll"
    }
   ]
  },
  {
   "title": "# Postfix Emails to Postfix daemon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postfix_emails_to_postfix_total{job=\"postfix\"}[5m]))",
     "legendFormat": "# Postfix emails to Postfix"
    }
   ]
  },
  {
   "title": "# Delivery Events",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(increase(delivered_events_total{job=\"backdata\"}[5m]))"
    }
   ]
  },
  { "title": "Inboxbooster Mailer Timeseries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Recipients and Deliveries (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(nbr_recipients_total{job=\"receiver\"}[5m]))\n",
     "legendFormat": "New Recipients (receiver)"
    },
    {
     "expr": "  sum(increase(delivered_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Delivered Events (Postfix -> Backdata)"
    }
   ]
  },
  {
   "title": "Non Delivery Events (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "  sum(increase(error_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "  sum(increase(bounced_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Bounced"
    },
    {
     "expr": "  sum(increase(spam_report_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Spam"
    },
    {
     "expr": "  sum(increase(unsubscribe_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Unsubscribe"
    },
    {
     "expr": "  sum(increase(malformed_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Malformed"
    },
    {
     "expr": "sum(increase(failed_pushed_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Failed to post event 400/500"
    }
   ]
  },
  {
   "title": "Throughput (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(nbr_emails_enqueued_total{job=\"receiver\"}[5m]))",
     "legendFormat": "# Receiver Push"
    },
    {
     "expr": "sum(increase(transformer_polled_primary_total{job=\"transformer\"}[5m]))",
     "legendFormat": "# Transformer Poll Primary"
    },
    {
     "expr": "sum(increase(transformer_polled_default_total{job=\"transformer\"}[5m]))",
     "legendFormat": "# Transformer Poll Default"
    },
    {
     "expr": "sum(increase(transformer_pushed_total{job=\"transformer\"}[5m]))",
     "legendFormat": "# Transformer Push"
    },
    {
     "expr": "sum(increase(delivered_events_total{job=\"backdata\"}[5m]))\n+\nsum(increase(bounced_events_total{job=\"backdata\"}[5m]))\n+\nsum(increase(error_events_total{job=\"backdata\"}[5m]))\n+\nsum(increase(spam_report_events_total{job=\"backdata\"}[5m]))\n+\nsum(increase(unsubscribe_events_total{job=\"backdata\"}[5m]))\n+\nsum(increase(malformed_events_total{job=\"backdata\"}[5m]))\n",
     "legendFormat": "# Backdata Poll"
    },
    {
     "expr": "sum(increase(successfully_pushed_events_total{}[5m]))",
     "legendFormat": "# Backdata Ok Push"
    },
    {
     "expr": "sum(increase(postfix_emails_polled_total{job=\"postfix\"}[5m]))",
     "legendFormat": "# Postfix Poll Email"
    },
    {
     "expr": "sum(increase(postfix_emails_to_postfix_total{job=\"postfix\"}[5m]))",
     "legendFormat": "# Postfix email to Postfix"
    }
   ]
  },
  {
   "title": "MxServer (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(mxserver_received_unsubscribe_total{job=\"mx-server\"}[5m]))",
     "legendFormat": "# Unsubscribe"
    },
    {
     "expr": "sum(increase(mxserver_received_unclassified_total{job=\"mxserver\"}[5m]))",
     "legendFormat": "# Unclassified"
    },
    {
     "expr": "sum(increase(mxserver_received_unsubscribe_total{job=\"mx-server\"}[5m]))",
     "legendFormat": "# Autoreply"
    }
   ]
  },
  {
   "title": "Postfix Internal Queues (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max_over_time(\n  postfix_incoming_queue_messages{job=\"postfix\"}[5m]\n)",
     "legendFormat": "postfix/incoming"
    },
    {
     "expr": "max_over_time(\n  postfix_active_queue_messages{job=\"postfix\"}[5m]\n)",
     "legendFormat": "postfix/active"
    },
    {
     "expr": "max_over_time(\n  postfix_deferred_queue_messages{job=\"postfix\"}[5m]\n)",
     "legendFormat": "postfix/deferred"
    },
    {
     "expr": "max_over_time(\n  postfix_corrupt_queue_messages{job=\"postfix\"}[5m]\n)",
     "legendFormat": "postfix/corrupt"
    },
    {
     "expr": "max_over_time(\n  postfix_hold_queue_messages{job=\"postfix\"}[5m]\n)",
     "legendFormat": "postfix/hold"
    }
   ]
  },
  {
   "title": "Redis Queue Sizes (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max_over_time(\n  primary_queue_messages{job=\"redis\", container=\"redis\"}[5m]\n)",
     "legendFormat": "Priority/Primary"
    },
    {
     "expr": "max_over_time(\n  default_queue_messages{job=\"redis\", container=\"redis\"}[5m]\n)",
     "legendFormat": "Slow/Default"
    },
    {
     "expr": "max_over_time(\n  event_queue_messages{job=\"redis\", container=\"redis\"}[5m]\n)",
     "legendFormat": "Event"
    },
    {
     "expr": "max_over_time(\n  queue_to_postfix_messages{job=\"redis\", container=\"redis\"}[5m]\n)",
     "legendFormat": "Queue to Postfix"
    }
   ]
  },
  {
   "title": "Number of Events currently posting in Backdata (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max_over_time(\n  number_of_events_currently_posting{job=\"backdata\"}[5m]\n)",
     "legendFormat": "Number of events being posted"
    }
   ]
  },
  {
   "title": "Warnings (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(receiver_warnings_total{job=\"receiver\"}[5m]))\n",
     "legendFormat": "Receiver"
    },
    {
     "expr": "sum(increase(transformer_warnings_total{job=\"transformer\"}[5m]))\n",
     "legendFormat": "Transformer"
    },
    {
     "expr": "sum(increase(postfix_poller_warnings_total{job=\"postfix\"}[5m]))\n",
     "legendFormat": "Postfix"
    },
    {
     "expr": "sum(increase(mxserver_warnings_total{job=\"mxserver\"}[5m]))\n",
     "legendFormat": "MxServer"
    },
    {
     "expr": "sum(increase(failed_pushed_events_total{job=\"backdata\"}[5m]))",
     "legendFormat": "Backdata"
    }
   ]
  },
  {
   "title": "Memory  Usage Host Server % (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"receiver\"}[5m]\n)",
     "legendFormat": "Receiver"
    },
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"transformer\"}[5m]\n)",
     "legendFormat": "Transformer"
    },
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"postfix\"}[5m]\n)",
     "legendFormat": "Postfix"
    },
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"backdata\"}[5m]\n)",
     "legendFormat": "Backdata"
    },
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"mxserver\"}[5m]\n)",
     "legendFormat": "MxServer"
    },
    {
     "expr": "max_over_time(\n  memory_usage_percent{job=\"redis\"}[5m]\n)",
     "legendFormat": "Redis"
    }
   ]
  }
 ]
}