apiVersion: v1
kind: Service
metadata:
  name: httpreceiver
  labels:
    app.kubernetes.io/name: httpreceiver
    environment: production
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: httpreceiver
  selector:
    app: httpreceiver
