{{- if .Values.postfix.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inboxbooster-mailer.postfix.serviceAccountName" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
  {{- if .Values.postfix.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.postfix.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
