apiVersion: v1
kind: Service
metadata:
  name: {{ include "inboxbooster-mailer.postfix.fullname" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postfix.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inboxbooster-mailer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postfix