# kubectl create -f pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: backdata
  labels:
    environment: production
    app.kubernetes.io/name: backdata
spec:
  containers:
    - name: backdata
      image: inboxbooster/backdata
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
