apiVersion: v1
kind: Service
metadata:
  name: backdata
  labels:
    app.kubernetes.io/name: backdata
    environment: production
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: backdata
  selector:
    app.kubernetes.io/name: backdata
    environment: production
