# kubectl create -f pod.yaml

# minicube tests. First line overrides docker repo to minicube.
# eval $(minikube -p minikube docker-env)
# docker build -t inboxbooster/receiver:latest .

apiVersion: v1
kind: Pod
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  containers:
    - name: receiver
      image: inboxbooster/receiver
      ports:
        - containerPort: 587
          name: smtp
        - containerPort: 9090
          name: prometheus
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command: [
              "python3", "/app/shutdown.py",
              "--global-config-file=/configs/inboxbooster-mailer-global.yaml",
              "--customer-config-file=/configs/inboxbooster-mailer-customer.yaml"
            ]
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
