# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  containers:
    - name: postfix
      image: inboxbooster/postfix:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 9090
          name: prometheus
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      lifecycle:
        preStop:
          exec:
            command: [
              "/bin/sh",
              "-c",
              "python3 /app/shutdown.py --global-config-file=/configs/inboxbooster-mailer-global.yaml --customer-config-file=/configs/inboxbooster-mailer-customer.yaml > /proc/1/fd/1 2> /proc/1/fd/1"
            ]
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
