# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  containers:
    - name: postfix
      image: inboxbooster/postfix
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
