apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app.kubernetes.io/name: postfix
    environment: production
spec:
  ports:
  - port: 25
    targetPort: 25
    name: postfix
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: postfix
