# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: transformer
  labels:
    app: transformer
spec:
  containers:
    - name: transformer
      image: inboxbooster/transformer
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
      imagePullPolicy: Always
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
