# kubectl create -f pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: transformer
spec:
  containers:
    - name: transformer
      image: inboxbooster/transformer
      volumeMounts:
        - name: configs
          mountPath: "/configs"
          readOnly: true
  volumes:
    - name: configs
      configMap:
        name: inboxbooster-config
