# kubectl create -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: transformer
  labels:
    app.kubernetes.io/name: transformer
    environment: production
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: transformer
