apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inboxbooster-mailer.redis.fullname" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "inboxbooster-mailer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  {{- if .Values.redis.updateStrategy }}
  strategy: {{- toYaml .Values.redis.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.redis.podAnnotations }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.redis.podAnnotations }}
        {{- toYaml .Values.redis.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "inboxbooster-mailer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inboxbooster-mailer.redis.serviceAccountName" . }}
      {{- if .Values.redis.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.redis.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          {{- if .Values.redis.securityContext.enabled }}
          securityContext:
            {{- omit .Values.redis.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.redisPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.redis.service.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: global-config
              mountPath: "/configs/inboxbooster-mailer-global.yaml"
              subPath: "inboxbooster-mailer-global.yaml"
              readOnly: true
            - name: custom-config
              mountPath: "/configs/inboxbooster-mailer-customer.yaml"
              subPath: "inboxbooster-mailer-customer.yaml"
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command:
                  - "python3"
                  - "/app/shutdown.py"
                  - "--global-config-file=/configs/inboxbooster-mailer-global.yaml"
                  - "--customer-config-file=/configs/inboxbooster-mailer-customer.yaml"
          {{- if .Values.redis.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.redis.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.redis.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.redis.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.redis.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.redis.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: global-config
          configMap:
            name: {{ printf "%s-global-config" (include "inboxbooster-mailer.fullname" .) }}
        - name: custom-config
          configMap:
            name: {{ .Values.config.existingConfigMap }}
      {{- if .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.redis.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.affinity }}
      affinity:
        {{- toYaml .Values.redis.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.tolerations }}
      tolerations:
        {{- toYaml .Values.redis.tolerations | nindent 8 }}
      {{- end }}
