{{- if .Values.redis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inboxbooster-mailer.redis.serviceAccountName" . }}
  labels:
    {{- include "inboxbooster-mailer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- if .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.redis.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
