apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    environment: production
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: redis
